language: rust
rust:
    - stable
cache: cargo
addons:
    apt:
        packages:
            - libx11-dev
            - libvulkan-dev
            - libxcb1-dev
            - xorg-dev
script:
    - cargo build
before_deploy:
    - git config --local user.name "travis"
    - git config --local user.email "yatekii@yatekii.ch"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
    - cd ..
    - mkdir sailor
    - cp ${REPO}target/release/sailor sailor
    - cp ${REPO}config sailor
    - zip -r ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.zip sailor
deploy:
  provider: releases
  api_key:
    secure: qOkRsLyj0I/sK4z09WSwaXXejKivpMkOSgLPfco4m60xCIkrtf0+HfVVuvVlZGGr1lff855rW5130PZrW5hg6Q/J3YSjEZnPwky7U5VkGGMMG9cNhYRn7SDfx+x9XD4ltfZAPX7fkisA7SCHFo6kuA6W5yawqRhUWT9Wl6A/4eN6i5j5jewZXt7uzyKCTrfsIHCZx4kPVLdLj7xWMjlTg2ZPuLvyKTXRjEnsoQOxFU5O3dGPuliMeTDlj/AAi7mBJ704Sz/LHybJodS2Mbq0HeK49Npj/o+fsSEq+wtRDJ5ntUUv9VCrJhwtMxXzPMOnLH1hCbj5y64iCWHQ6o4WsCum2hJmVtiv3iREAkd+UtL/JWkC3ir8dd145HFVPYaAQ4LcO5zXAPudVuJY+AI4QYpTl2XCsYrEQFiEBjlCs5xsDpHMnkSKrGcBQh/pPbJm9JkLVxk/+5VvK8Iv96h9Wvv0FDJqgh2y72HyLLryLlyx9dZpOCO9uqfjQn5FBrl1E7R8HHYsfczqS+keZgh/49Xe4TsgTIEM6G7Zx8MSLxhQDrQLvL3x8IF4DLT8s0sZXg4/U65cDEFaHMQfiE8bADOSadS7jvptq9izjRwarEig5cZbpe0GHpcG7garMri58k4h8gUtk7fiLiK6tRZL/eepebwSReSjUvY/6MrIuv0=
  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.zip
  on:
    repo: Yatekii/sailor
    tags: true
    all_branches: true