language: rust
rust:
    - stable
cache: cargo
addons:
    apt:
        packages:
            - libx11-dev
            - libvulkan-dev
            - libxcb1-dev
            - xorg-dev
script:
    - cargo build --release
before_deploy:
    - git config --local user.name "travis"
    - git config --local user.email "yatekii@yatekii.ch"
    - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
    - git tag $TRAVIS_TAG
    - mkdir sailor
    - cp ${REPO}target/release/sailor sailor
    - cp -r ${REPO}config sailor
    - zip -r ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.zip sailor
deploy:
  provider: releases
  api_key:
    secure: NThHfJOHZv3rXCUPZ5SEdk0zm1xlCwEk0QHYuWatd2aN0WUmAIF3nr+G+2Or5W1tgUxdBKHwSzPvETUQjBiFTItM9/fTnqtkKXHAtCsZP2lpEiji1REreFwjGGb1F/ugH0DOsgKtoMrbNTs8cbEWN5wS77DlJH1jYd2WoAFIVNrMrVtSDFM/X1DiJTW2t4rRCOQDvfHjF7fc9ZHE77TdpB+LMtT1px4Ir+nNMG15xBRzMxXIwY1ts6uJHrBhGACcK8OTlyVpbUqB5obpP+54MJFYXAi+cwqFptaekugxX/Gyq5MWjLeAHmmMI32R9AZd4CnJOkICtJztARfgYOo23v623Mpy57dFpH8zD+INMkafeK8twJ774FRsU8adkbcyMGm044fY+n2giwlYaRBQasrSVH3JVWiQNxu7yVvNz5tkpMPOwblKZjQAlg5ZdGR0IxEiQv76n9rx17k57NuuDTjS++r2r6mWDMBNP5nsBveiiDMUeRxkbF/pz7bRX7eKOQI8A1pOjlAM57fXhMze5m77McFFpHvvoHdB1oZzaWAyYI2kLfnsDCjdw2HbCOfLWIM+jOK3vnCMvcfwE/CfrXa88K6E6syI51UboAtHmsLqxfOiMASMujPNuKHA7N+ZkDVWVjFYNJx36Sklp02Q46j6QKoMtY1Keie8oVgUyYY=
  file: ${TRAVIS_BUILD_DIR}${REPO}-${BUILD_ENV}-${TRAVIS_TAG}-${TRAVIS_BUILD_NUMBER}.zip
  on:
    repo: Yatekii/sailor
    all_branches: true