[package]
name = "sailor"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

description = "A sailing navigation application."
documentation = "https://docs.rs/sailor/"
homepage = "https://github.com/Yatekii/sailor"
repository = "https://github.com/Yatekii/sailor"
readme = "README.md"
categories = ["gui", "graphics", "rendering", "visualization", "science"]
keywords = ["sailing", "osm", "gps", "wgpu", "maps"]
license = "MIT OR Apache-2.0"

autobins = false

[lib]
name = "osm"
path = "src/lib/main.rs"

[[bin]]
name = "sailor"
path = "src/bin/main.rs"

[dependencies]
quick-protobuf = "0.8"
lyon = "0.13"
varint = "0.9"
ureq = "1.5"
nalgebra = "0.23"
nalgebra-glm = "0.9"
nom = "6.0"
notify = "5.0.0-pre.4"
crossbeam-channel = "0.5"
wgpu = "0.5"
winit = "0.21"
serde = "1.0"
serde_derive = "1.0"
once_cell = "1.4"
config = "0.10"
pretty_env_logger = "0.4"
log = { version = "0.4", features = ["serde"] }
shaderc = "0.6"
imgui = "0.3"
imgui-wgpu = "0.6"
ncollide2d = "0.26"
parity-util-mem = "0.7"
malloc_size_of_derive = "0.1"
wgpu_glyph = "0.8"
pollster = "0.2"

[dependencies.imgui-winit-support]
version = "0.3"
default-features = false
features = ["winit-20"]
