[package]
name = "sailor"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[dependencies]
structopt = "*"
quick-protobuf = "*"
lyon = "*"
glium = "0.22.0"
varint = "*"
reqwest = "*"
nalgebra = "*"
lyon_tess2 = "*"