[package]
name = "sailor"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

description = "A sailing navigation application."
documentation = "https://docs.rs/sailor/"
homepage = "https://github.com/Yatekii/sailor"
repository = "https://github.com/Yatekii/sailor"
readme = "README.md"
categories = ["gui", "graphics", "rendering", "visualization", "science"]
keywords = ["sailing", "osm", "gps", "wgpu", "maps"]
license = "MIT OR Apache-2.0"

autobins = false

[lib]
name = "osm"
path = "src/lib/main.rs"

[[bin]]
name = "sailor"
path = "src/bin/main.rs"

[profile.release]
debug = true

[dependencies]
quick-protobuf = "0.6.3"
lyon = "0.13.2"
varint = "0.9.0"
reqwest = "0.9.18"
nalgebra = "0.18.0"
nalgebra-glm = "0.4.0"
nom = "5.0.0-beta2"
notify = "5.0.0-pre.0"
crossbeam-channel = "0.3.8"
wgpu = { version = "0.3.0", features = ["vulkan"] }
winit = "0.20.0-alpha3"
serde = "1.0.99"
serde_derive = "1.0.99"
lazy_static = "1.3.0"
config = "0.9.3"
pretty_env_logger = "0.3.0"
log = { version = "0.4.7", features = ["serde"] }
glsl-to-spirv = "0.1"
num-traits = "0.2.8"
imgui = "0.2.0"
imgui-wgpu = { version = "0.1.0", features = ["vulkan"] }
ncollide2d = "0.20.1"
raw-window-handle = "0.1"
parity-util-mem = "0.2.0"
malloc_size_of_derive = "0.1.0"
size_format = "1.0.2"
derivative = "1.0.3"
wgpu_glyph = "0.4.0"

[dependencies.imgui-winit-support]
version = "0.2.0"
default-features = false
features = ["winit-20"]