[package]
name = "sailor"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

[profile.release]
# debug = true

[dependencies]
structopt = "*"
quick-protobuf = "*"
lyon = "*"
euclid = "*"
varint = "*"
reqwest = "*"
nalgebra = "*"
nalgebra-glm = "0.4"
rayon = "*"
nom = "5.0.0-beta2"
notify = "5.0.0-pre.0"
crossbeam-channel = "*"
take_mut = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", features = ["vulkan"] }
# wgpu = { path = "../wgpu-rs", features = ["vulkan"] }
pretty_env_logger = "0.3.0"
log = "0.4.6"
glsl-to-spirv = "0.1"
phf = { version = "*", features = ["macros"] }