[package]
name = "sailor"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

description = "A sailing navigation application."
documentation = "https://docs.rs/sailor/"
homepage = "https://github.com/Yatekii/sailor"
repository = "https://github.com/Yatekii/sailor"
readme = "README.md"
categories = ["gui", "graphics", "rendering", "visualization", "science"]
keywords = ["sailing", "osm", "gps", "wgpu", "maps"]
license = "MIT OR Apache-2.0"

autobins = false

[lib]
name = "osm"
path = "src/lib/main.rs"

[[bin]]
name = "sailor"
path = "src/bin/main.rs"

[dependencies]
quick-protobuf = "0.8.0"
lyon = "0.13.2"
varint = "0.9.0"
ureq = "1.5.1"
nalgebra = "0.22.0"
nalgebra-glm = "0.8.0"
nom = "5.0.0-beta2"
notify = "5.0.0-pre.3"
crossbeam-channel = "0.4.4"
wgpu = "0.5.0"
winit = "0.21.0"
serde = "1.0.99"
serde_derive = "1.0.99"
lazy_static = "1.3.0"
config = "0.10.1"
pretty_env_logger = "0.4.0"
log = { version = "0.4.7", features = ["serde"] }
glsl-to-spirv = "0.1"
num-traits = "0.2.8"
imgui = "0.3.0"
imgui-wgpu = "0.6.0"
ncollide2d = "0.25.0"
raw-window-handle = "0.3.3"
parity-util-mem = "0.7.0"
malloc_size_of_derive = "0.1.0"
size_format = "1.0.2"
derivative = "2.1.1"
wgpu_glyph = "0.8.0"
futures = "0.3"

[dependencies.imgui-winit-support]
version = "0.3.0"
default-features = false
features = ["winit-20"]
