[package]
name = "sailor"
version = "0.1.0"
authors = ["Noah Hüsser <yatekii@yatekii.ch>"]
edition = "2018"

description = "A sailing navigation application."
documentation = "https://docs.rs/sailor/"
homepage = "https://github.com/Yatekii/sailor"
repository = "https://github.com/Yatekii/sailor"
readme = "README.md"
categories = []
keywords = ["sailing", "gfx", "gps"]
license = "MIT OR Apache-2.0"

[features]
default = ["vulkan"]
gl = []
vulkan = []

[profile.release]
debug = true

[dependencies]
structopt = "*"
quick-protobuf = "*"
lyon = "*"
euclid = "*"
varint = "*"
reqwest = "*"
nalgebra = "*"
nalgebra-glm = "0.4"
rayon = "*"
nom = "5.0.0-beta2"
notify = "5.0.0-pre.0"
crossbeam-channel = "*"
take_mut = "*"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git", features = ["vulkan"], rev="4233fee6e21f22362a019691d7c9643b0d6068d2" }
# wgpu = { package = "wgpu", features = ["vulkan"], git = "https://github.com/Yatekii/wgpu-rs" }
# wgpu = { package = "wgpu", features = ["vulkan"], git = "https://github.com/Yatekii/wgpu-rs", branch = "stencil" }
# wgpu = { package = "wgpu", features = ["vulkan"], path = "../wgpu-rs" }
pretty_env_logger = "0.3.0"
log = "0.4.6"
glsl-to-spirv = "0.1"
phf = { version = "*", features = ["macros"] }