[general]
display-framerate = false
data-root = ""

[general.log]
level = "WARN"

[renderer]
vertex-shader = "config/shader.vert"
fragment-shader = "config/shader.frag"
css = "config/style.css"
ui-font = "config/Ruda-Bold.ttf"
max-tiles = 200
max-features = 1000
tile-size = 384
msaa-samples = 4
selection-tags = []

[renderer.temperature]
vertex-shader = "config/temperature/shader.vert"
fragment-shader = "config/temperature/shader.frag"

[map.initial]
zoom = 13.0

[map.initial.center]
latitude = 47.3769
longitude = 8.5417
