[general]
log_level = "Warn"
display_framerate = false

[renderer]
vertex_shader = "config/shader.vert"
fragment_shader = "config/shader.frag"
css = "config/style.css"
max_tiles = 200
max_features = 1001
tile_size = 384
msaa_samples = 1
