general:
  display-framerate: false
  data-root: "cache"
  log:
    level: "WARN"

window:
  size:
    windowed:
      width: 1200
      height: 800
    # Fullscreen:

renderer:
  vertex-shader: "config/shader.vert"
  fragment-shader: "config/shader.frag"
  css: "config/style.css"
  ui-font: "config/Ruda-Bold.ttf"
  tile-size: 512
  msaa-samples: 4
  selection-tags: []

map:
  initial:
    zoom: 13.0
    center:
      latitude: 47.3769
      longitude: 8.5417
