[general]
log_level = "Warn"
display_framerate = false

[renderer]
vertex_shader = "config/shader.vert"
fragment_shader = "config/shader.frag"
css = "config/style.css"
ui_font = "config/Ruda-Bold.ttf"
max_tiles = 200
max_features = 10001
tile_size = 384
msaa_samples = 1
selection_tags = []